from sqlalchemy.ext.asyncio import AsyncSession

from app.entities import UserModel
from app.seeders.base_seeder import BaseSeeder
from app.shared.app_constants import AppTableNames


class UserSeeder(BaseSeeder):
    async def seed(self, session: AsyncSession):
        data = self.get_data()
        await self.load_seeders(UserModel, session, AppTableNames.UserTableName, data)

    def get_dev_data(self):
        return [
            UserModel(
                id=1,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-0",
                iin="970327300931",
                role_id=7,
                type_id=1,
                file_id=None,
                name="Ширинов Абай",
                given_name=None,
                family_name=None,
                preferred_username="shirinov.abai",
                email="mistier.famous@gmail.com",
                email_verified=False,
                phone="+77064205962",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=2,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-1",
                iin="970327300930",
                role_id=7,
                type_id=2,
                file_id=None,
                name="Ширинов Абай Калдыбекович",
                given_name=None,
                family_name=None,
                preferred_username="abai.kaldybekovich",
                email="kazitech2023@gmail.com",
                email_verified=False,
                phone="+77064205961",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=3,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-3",
                iin="931011256985",
                role_id=7,
                type_id=2,
                file_id=None,
                name="Мухамедиев Дастан Бахытбекович",
                given_name=None,
                family_name=None,
                preferred_username="dastan.mukhamediev_local",
                email="iutest@gmail.com",
                email_verified=False,
                phone="+77064205963",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=4,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-4",
                iin="961011256524",
                role_id=7,
                type_id=1,
                file_id=None,
                name="Акилбеков Нурбакыт Ниязбекович",
                given_name=None,
                family_name=None,
                preferred_username="nurbakyt.akilbekov_local",
                email="nurbakit@gmail.com",
                email_verified=False,
                phone="+77064171796",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=5,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-5",
                iin="222222222222",
                role_id=2,
                type_id=1,
                file_id=None,
                name="Служба безопасности завода",
                given_name=None,
                family_name=None,
                preferred_username="security.factory_local",
                email="security@gmail.com",
                email_verified=False,
                phone="+77062222222",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=6,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-6",
                iin="333333333333",
                role_id=3,
                type_id=1,
                file_id=None,
                name="Охраник Погрузчиков",
                given_name=None,
                family_name=None,
                preferred_username="security.loader_local",
                email="security_loader@gmail.com",
                email_verified=False,
                phone="+77063333333",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=7,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-7",
                iin="444444444444",
                role_id=4,
                type_id=1,
                file_id=None,
                name="Погрузчик Погрузчиков",
                given_name=None,
                family_name=None,
                preferred_username="loader.operator_local",
                email="loader@gmail.com",
                email_verified=False,
                phone="+770644444444",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=8,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-8",
                iin="555555555555",
                role_id=5,
                type_id=1,
                file_id=None,
                name="Весовщик Весовщиков",
                given_name=None,
                family_name=None,
                preferred_username="weigher.operator_local",
                email="weigher@gmail.com",
                email_verified=False,
                phone="+77065555555",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=9,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-9",
                iin="100200300400",
                role_id=1,
                type_id=1,
                file_id=None,
                name="Система Цифровой Очереди",
                given_name=None,
                family_name=None,
                preferred_username="admin.queue_local",
                email="admin@gmail.com",
                email_verified=False,
                phone="+77068495961",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
            UserModel(
                id=10,
                sid="c3732b90-58e0-4062-8b46-4420666d0361-10",
                iin="100200300499",
                role_id=6,
                type_id=1,
                file_id=None,
                name="Бухгалтер",
                given_name=None,
                family_name=None,
                preferred_username="accountant_local",
                email="buh@gmail.com",
                email_verified=False,
                phone="+77068495907",
                phone_verified=False,
                tabn=None,
                status=True,
                password_hash="$2b$12$zhSpWTELxX8/N274Gy4wkOetqv02re2AYEv2LiXmGn4V4wCme6Hqe",
            ),
        ]

    def get_prod_data(self):
        return self.get_data()

    def get_dev_updated_data(self):
        pass

    def get_prod_updated_data(self):
        pass
