"""Add Order Id to Sap Transfer

Revision ID: 01fae65cb8b9
Revises: dff5a33f1f81
Create Date: 2024-12-28 19:00:18.813017

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01fae65cb8b9"
down_revision: Union[str, None] = "dff5a33f1f81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sap_transfers", sa.Column("order_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "sap_transfers",
        "orders",
        ["order_id"],
        ["id"],
        onupdate="cascade",
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sap_transfers", type_="foreignkey")
    op.drop_column("sap_transfers", "order_id")
    # ### end Alembic commands ###
