"""Add Order Id to Kaspi Payment

Revision ID: 04885350c86a
Revises: e6fd840a58ca
Create Date: 2024-12-28 16:31:33.202580

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04885350c86a"
down_revision: Union[str, None] = "e6fd840a58ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kaspi_payments", sa.Column("order_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "kaspi_payments",
        "orders",
        ["order_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "kaspi_payments", type_="foreignkey")
    op.drop_column("kaspi_payments", "order_id")
    # ### end Alembic commands ###
