"""Add Workshop SAP Id to Material

Revision ID: 34962b418ed8
Revises: d21ca7453cd2
Create Date: 2024-12-28 17:00:23.756823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34962b418ed8'
down_revision: Union[str, None] = 'd21ca7453cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('workshop_sap_id', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_materials_workshop_sap_id'), 'materials', ['workshop_sap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_workshop_sap_id'), table_name='materials')
    op.drop_column('materials', 'workshop_sap_id')
    # ### end Alembic commands ###
