"""Add Workshop SAP Id to Order

Revision ID: 7a4f26cd1735
Revises: 34962b418ed8
Create Date: 2024-12-28 17:17:03.783108

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a4f26cd1735"
down_revision: Union[str, None] = "34962b418ed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("sap_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "orders",
        "sap_requests",
        ["sap_id"],
        ["id"],
        onupdate="cascade",
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "sap_id")
    # ### end Alembic commands ###
