"""Change Schdedule Vehicle to Zero

Revision ID: 9f24e08e7b30
Revises: f8d3fec27bbf
Create Date: 2025-01-13 19:21:50.229839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f24e08e7b30'
down_revision: Union[str, None] = 'f8d3fec27bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
