"""Added prev and next value to Operation

Revision ID: a155d6ccf52b
Revises: ae50f7d6377f
Create Date: 2024-12-27 12:39:09.105557

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a155d6ccf52b"
down_revision: Union[str, None] = "ae50f7d6377f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operations", sa.Column("prev_value", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "operations", sa.Column("next_value", sa.String(length=256), nullable=True)
    )
    op.create_index(
        op.f("ix_operations_next_value"), "operations", ["next_value"], unique=False
    )
    op.create_index(
        op.f("ix_operations_prev_value"), "operations", ["prev_value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operations_prev_value"), table_name="operations")
    op.drop_index(op.f("ix_operations_next_value"), table_name="operations")
    op.drop_column("operations", "next_value")
    op.drop_column("operations", "prev_value")
    # ### end Alembic commands ###
