"""Removed quan

Revision ID: a74903a69b40
Revises: 2064488f7fa7
Create Date: 2025-01-09 12:00:40.826956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74903a69b40'
down_revision: Union[str, None] = '2064488f7fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quan_left_t')
    op.drop_column('orders', 'quan_left')
    op.drop_column('orders', 'quan_booked_t')
    op.drop_column('orders', 'quan_booked')
    op.drop_column('orders', 'quan_released_t')
    op.drop_column('orders', 'quan_released')
    op.drop_column('orders', 'quan')
    op.drop_column('orders', 'quan_t')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quan_left_t', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((((((quan_t * (1000)::numeric))::integer - quan_booked) - quan_released))::numeric / 1000.0)', persisted=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_left', sa.INTEGER(), sa.Computed('((((quan_t * (1000)::numeric))::integer - quan_booked) - quan_released)', persisted=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_booked_t', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((quan_booked)::numeric / 1000.0))::double precision', persisted=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_booked', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_released_t', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((quan_released)::numeric / 1000.0))::double precision', persisted=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_released', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan', sa.INTEGER(), sa.Computed('((quan_t * (1000)::numeric))::integer', persisted=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quan_t', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
