"""Added prev and next value to Order Status

Revision ID: ae50f7d6377f
Revises: 1834c60c13f8
Create Date: 2024-12-27 11:38:29.688642

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae50f7d6377f"
down_revision: Union[str, None] = "1834c60c13f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_status", sa.Column("prev_value", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "order_status", sa.Column("next_value", sa.String(length=256), nullable=True)
    )
    op.create_index(
        op.f("ix_order_status_next_value"), "order_status", ["next_value"], unique=False
    )
    op.create_index(
        op.f("ix_order_status_prev_value"), "order_status", ["prev_value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status_prev_value"), table_name="order_status")
    op.drop_index(op.f("ix_order_status_next_value"), table_name="order_status")
    op.drop_column("order_status", "next_value")
    op.drop_column("order_status", "prev_value")
    # ### end Alembic commands ###
