"""Basic Table Migration: 16 tables

Revision ID: b62c29b92bd6
Revises: 
Create Date: 2024-12-26 10:31:20.761811

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b62c29b92bd6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sap_id", sa.String(length=256), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_factories_sap_id"), "factories", ["sap_id"], unique=True)
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kaspi_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zakaz", sa.String(length=256), nullable=False),
        sa.Column("account", sa.String(length=256), nullable=False),
        sa.Column("txn_id", sa.String(length=256), nullable=True),
        sa.Column("txn_check_id", sa.String(length=256), nullable=True),
        sa.Column("txn_pay_id", sa.String(length=256), nullable=True),
        sa.Column("txn_date", sa.String(length=256), nullable=True),
        sa.Column("command", sa.String(length=256), nullable=True),
        sa.Column("sum", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("is_failed", sa.Boolean(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("is_qr_generate", sa.Boolean(), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kaspi_payments_account"), "kaspi_payments", ["account"], unique=False
    )
    op.create_index(
        op.f("ix_kaspi_payments_command"), "kaspi_payments", ["command"], unique=False
    )
    op.create_index(
        op.f("ix_kaspi_payments_txn_check_id"),
        "kaspi_payments",
        ["txn_check_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kaspi_payments_txn_id"), "kaspi_payments", ["txn_id"], unique=False
    )
    op.create_index(
        op.f("ix_kaspi_payments_txn_pay_id"),
        "kaspi_payments",
        ["txn_pay_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kaspi_payments_zakaz"), "kaspi_payments", ["zakaz"], unique=False
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sap_id", sa.String(length=256), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "price_without_taxes", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "price_with_taxes", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_materials_sap_id"), "materials", ["sap_id"], unique=True)
    op.create_table(
        "order_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("prev_id", sa.Integer(), nullable=True),
        sa.Column("next_id", sa.Integer(), nullable=True),
        sa.Column("is_first", sa.Boolean(), nullable=False),
        sa.Column("is_last", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["next_id"], ["order_status.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["prev_id"], ["order_status.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_value"), "order_status", ["value"], unique=True
    )
    op.create_table(
        "organization_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_types_value"),
        "organization_types",
        ["value"],
        unique=True,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("keycloak_id", sa.String(length=256), nullable=True),
        sa.Column("keycloak_value", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_value"), "roles", ["value"], unique=True)
    op.create_table(
        "user_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("keycloak_id", sa.String(length=256), nullable=True),
        sa.Column("keycloak_value", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_types_value"), "user_types", ["value"], unique=True)
    op.create_table(
        "vehicle_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_categories_value"),
        "vehicle_categories",
        ["value"],
        unique=True,
    )
    op.create_table(
        "vehicle_colors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_colors_value"), "vehicle_colors", ["value"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sid", sa.String(length=256), nullable=False),
        sa.Column("iin", sa.String(length=12), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("given_name", sa.String(length=256), nullable=True),
        sa.Column("family_name", sa.String(length=256), nullable=True),
        sa.Column("preferred_username", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=256), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("tabn", sa.String(length=256), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["user_types.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_iin"), "users", ["iin"], unique=True)
    op.create_index(
        op.f("ix_users_preferred_username"),
        "users",
        ["preferred_username"],
        unique=True,
    )
    op.create_index(op.f("ix_users_sid"), "users", ["sid"], unique=True)
    op.create_table(
        "workshops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sap_id", sa.String(length=256), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("factory_id", sa.Integer(), nullable=True),
        sa.Column("factory_sap_id", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"], ["factories.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workshops_factory_sap_id"),
        "workshops",
        ["factory_sap_id"],
        unique=False,
    )
    op.create_index(op.f("ix_workshops_sap_id"), "workshops", ["sap_id"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=False),
        sa.Column("bin", sa.String(length=12), nullable=False),
        sa.Column("bik", sa.String(length=256), nullable=True),
        sa.Column("kbe", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("phone", sa.String(length=256), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["organization_types.id"],
            onupdate="cascade",
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_bin"), "organizations", ["bin"], unique=True)
    op.create_index(
        op.f("ix_organizations_email"), "organizations", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_organizations_phone"), "organizations", ["phone"], unique=True
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=256), nullable=False),
        sa.Column("factory_id", sa.Integer(), nullable=True),
        sa.Column("factory_sap_id", sa.String(length=256), nullable=False),
        sa.Column("workshop_id", sa.Integer(), nullable=True),
        sa.Column("workshop_sap_id", sa.String(length=256), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("material_sap_id", sa.String(length=256), nullable=False),
        sa.Column("quan_t", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "quan",
            sa.Integer(),
            sa.Computed("(quan_t * 1000)::INTEGER", persisted=True),
            nullable=False,
        ),
        sa.Column("quan_released", sa.Integer(), nullable=False),
        sa.Column(
            "quan_released_t",
            sa.Float(),
            sa.Computed("(quan_released / 1000.0)::DOUBLE PRECISION", persisted=True),
            nullable=False,
        ),
        sa.Column("quan_booked", sa.Integer(), nullable=False),
        sa.Column(
            "quan_booked_t",
            sa.Float(),
            sa.Computed("(quan_booked / 1000.0)::DOUBLE PRECISION", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "quan_left",
            sa.Integer(),
            sa.Computed(
                "(quan_t * 1000)::INTEGER - quan_booked - quan_released", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "quan_left_t",
            sa.Float(),
            sa.Computed(
                "((quan_t * 1000)::INTEGER - quan_booked - quan_released) / 1000.0",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("executed_cruise", sa.Integer(), nullable=False),
        sa.Column(
            "price_without_taxes", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "price_with_taxes", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("zakaz", sa.String(length=256), nullable=True),
        sa.Column("kaspi_id", sa.Integer(), nullable=True),
        sa.Column("txn_id", sa.String(length=256), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("iin", sa.String(length=256), nullable=True),
        sa.Column("owner_sid", sa.String(length=256), nullable=True),
        sa.Column("owner_username", sa.String(length=256), nullable=True),
        sa.Column("owner_email", sa.String(length=256), nullable=True),
        sa.Column("owner_mobile", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("adr_index", sa.String(length=256), nullable=True),
        sa.Column("adr_city", sa.String(length=256), nullable=True),
        sa.Column("adr_str", sa.String(length=256), nullable=True),
        sa.Column("adr_dom", sa.String(length=256), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("bin", sa.String(length=256), nullable=True),
        sa.Column("dogovor", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_finished", sa.Boolean(), nullable=False),
        sa.Column("is_failed", sa.Boolean(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("is_cancel", sa.Boolean(), nullable=False),
        sa.Column(
            "start_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_at", sa.DateTime(), nullable=True),
        sa.Column(
            "must_paid_at",
            sa.DateTime(),
            sa.Computed("(created_at + INTERVAL '1 day')", persisted=True),
            nullable=True,
        ),
        sa.Column("canceled_by_user", sa.Integer(), nullable=True),
        sa.Column("canceled_by_sid", sa.String(length=256), nullable=True),
        sa.Column("canceled_by_name", sa.String(length=256), nullable=True),
        sa.Column("checked_payment_by_id", sa.Integer(), nullable=True),
        sa.Column("checked_payment_by", sa.String(length=256), nullable=True),
        sa.Column("checked_payment_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canceled_by_user"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["checked_payment_by_id"],
            ["users.id"],
            onupdate="cascade",
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"], ["factories.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["kaspi_id"], ["kaspi_payments.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            onupdate="cascade",
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["order_status.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"], ["workshops.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_bin"), "orders", ["bin"], unique=False)
    op.create_index(
        op.f("ix_orders_canceled_by_sid"), "orders", ["canceled_by_sid"], unique=False
    )
    op.create_index(op.f("ix_orders_dogovor"), "orders", ["dogovor"], unique=False)
    op.create_index(
        op.f("ix_orders_factory_sap_id"), "orders", ["factory_sap_id"], unique=False
    )
    op.create_index(op.f("ix_orders_iin"), "orders", ["iin"], unique=False)
    op.create_index(
        op.f("ix_orders_material_sap_id"), "orders", ["material_sap_id"], unique=False
    )
    op.create_index(
        op.f("ix_orders_owner_email"), "orders", ["owner_email"], unique=False
    )
    op.create_index(
        op.f("ix_orders_owner_mobile"), "orders", ["owner_mobile"], unique=False
    )
    op.create_index(op.f("ix_orders_owner_sid"), "orders", ["owner_sid"], unique=False)
    op.create_index(
        op.f("ix_orders_owner_username"), "orders", ["owner_username"], unique=False
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_txn_id"), "orders", ["txn_id"], unique=False)
    op.create_index(
        op.f("ix_orders_workshop_sap_id"), "orders", ["workshop_sap_id"], unique=False
    )
    op.create_index(op.f("ix_orders_zakaz"), "orders", ["zakaz"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("registration_number", sa.String(length=256), nullable=False),
        sa.Column("car_model", sa.String(length=256), nullable=False),
        sa.Column("is_trailer", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["vehicle_categories.id"],
            onupdate="cascade",
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["color_id"], ["vehicle_colors.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            onupdate="cascade",
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("checked_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], onupdate="cascade", ondelete="restrict"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], onupdate="cascade", ondelete="restrict"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sap_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("werks", sa.String(length=256), nullable=True),
        sa.Column("matnr", sa.String(length=256), nullable=False),
        sa.Column("kun_name", sa.String(length=256), nullable=True),
        sa.Column("iin", sa.String(length=256), nullable=True),
        sa.Column("quan", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("dogovor", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=256), nullable=True),
        sa.Column("zakaz", sa.String(length=256), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("pdf", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("time", sa.Time(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_failed", sa.Boolean(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sap_requests_zakaz"), "sap_requests", ["zakaz"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sap_requests_zakaz"), table_name="sap_requests")
    op.drop_table("sap_requests")
    op.drop_table("payment_documents")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_orders_zakaz"), table_name="orders")
    op.drop_index(op.f("ix_orders_workshop_sap_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_txn_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_owner_username"), table_name="orders")
    op.drop_index(op.f("ix_orders_owner_sid"), table_name="orders")
    op.drop_index(op.f("ix_orders_owner_mobile"), table_name="orders")
    op.drop_index(op.f("ix_orders_owner_email"), table_name="orders")
    op.drop_index(op.f("ix_orders_material_sap_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_iin"), table_name="orders")
    op.drop_index(op.f("ix_orders_factory_sap_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_dogovor"), table_name="orders")
    op.drop_index(op.f("ix_orders_canceled_by_sid"), table_name="orders")
    op.drop_index(op.f("ix_orders_bin"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_organizations_phone"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_email"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_bin"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_workshops_sap_id"), table_name="workshops")
    op.drop_index(op.f("ix_workshops_factory_sap_id"), table_name="workshops")
    op.drop_table("workshops")
    op.drop_index(op.f("ix_users_sid"), table_name="users")
    op.drop_index(op.f("ix_users_preferred_username"), table_name="users")
    op.drop_index(op.f("ix_users_iin"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_vehicle_colors_value"), table_name="vehicle_colors")
    op.drop_table("vehicle_colors")
    op.drop_index(op.f("ix_vehicle_categories_value"), table_name="vehicle_categories")
    op.drop_table("vehicle_categories")
    op.drop_index(op.f("ix_user_types_value"), table_name="user_types")
    op.drop_table("user_types")
    op.drop_index(op.f("ix_roles_value"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_organization_types_value"), table_name="organization_types")
    op.drop_table("organization_types")
    op.drop_index(op.f("ix_order_status_value"), table_name="order_status")
    op.drop_table("order_status")
    op.drop_index(op.f("ix_materials_sap_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_kaspi_payments_zakaz"), table_name="kaspi_payments")
    op.drop_index(op.f("ix_kaspi_payments_txn_pay_id"), table_name="kaspi_payments")
    op.drop_index(op.f("ix_kaspi_payments_txn_id"), table_name="kaspi_payments")
    op.drop_index(op.f("ix_kaspi_payments_txn_check_id"), table_name="kaspi_payments")
    op.drop_index(op.f("ix_kaspi_payments_command"), table_name="kaspi_payments")
    op.drop_index(op.f("ix_kaspi_payments_account"), table_name="kaspi_payments")
    op.drop_table("kaspi_payments")
    op.drop_table("files")
    op.drop_index(op.f("ix_factories_sap_id"), table_name="factories")
    op.drop_table("factories")
    # ### end Alembic commands ###
