"""Basic Table Migration: 12 tables

Revision ID: bce5971c0dbe
Revises: 
Create Date: 2024-12-24 18:03:53.354162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce5971c0dbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sap_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_sap_id'), 'factories', ['sap_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sap_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('price_without_taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_with_taxes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_sap_id'), 'materials', ['sap_id'], unique=True)
    op.create_table('organization_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_types_value'), 'organization_types', ['value'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('keycloak_id', sa.String(length=256), nullable=True),
    sa.Column('keycloak_value', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_value'), 'roles', ['value'], unique=True)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('keycloak_id', sa.String(length=256), nullable=True),
    sa.Column('keycloak_value', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_types_value'), 'user_types', ['value'], unique=True)
    op.create_table('vehicle_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_categories_value'), 'vehicle_categories', ['value'], unique=True)
    op.create_table('vehicle_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_colors_value'), 'vehicle_colors', ['value'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=256), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('given_name', sa.String(length=256), nullable=True),
    sa.Column('family_name', sa.String(length=256), nullable=True),
    sa.Column('preferred_username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('tabn', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['type_id'], ['user_types.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_iin'), 'users', ['iin'], unique=True)
    op.create_index(op.f('ix_users_preferred_username'), 'users', ['preferred_username'], unique=True)
    op.create_index(op.f('ix_users_sid'), 'users', ['sid'], unique=True)
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sap_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('factory_sap_id', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshops_factory_sap_id'), 'workshops', ['factory_sap_id'], unique=False)
    op.create_index(op.f('ix_workshops_sap_id'), 'workshops', ['sap_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('bik', sa.String(length=256), nullable=True),
    sa.Column('kbe', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=256), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['type_id'], ['organization_types.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_bin'), 'organizations', ['bin'], unique=True)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_phone'), 'organizations', ['phone'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=256), nullable=False),
    sa.Column('car_model', sa.String(length=256), nullable=False),
    sa.Column('is_trailed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_categories.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['color_id'], ['vehicle_colors.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], onupdate='cascade', ondelete='set null'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='cascade', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_organizations_phone'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_bin'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_workshops_sap_id'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_factory_sap_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_users_sid'), table_name='users')
    op.drop_index(op.f('ix_users_preferred_username'), table_name='users')
    op.drop_index(op.f('ix_users_iin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vehicle_colors_value'), table_name='vehicle_colors')
    op.drop_table('vehicle_colors')
    op.drop_index(op.f('ix_vehicle_categories_value'), table_name='vehicle_categories')
    op.drop_table('vehicle_categories')
    op.drop_index(op.f('ix_user_types_value'), table_name='user_types')
    op.drop_table('user_types')
    op.drop_index(op.f('ix_roles_value'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organization_types_value'), table_name='organization_types')
    op.drop_table('organization_types')
    op.drop_index(op.f('ix_materials_sap_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('files')
    op.drop_index(op.f('ix_factories_sap_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
