"""Changed Workshop Schedule

Revision ID: cd6ed654c657
Revises: a155d6ccf52b
Create Date: 2024-12-27 17:22:16.182832

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd6ed654c657"
down_revision: Union[str, None] = "a155d6ccf52b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshop_schedules",
        sa.Column("can_earlier_come_min", sa.Integer(), nullable=False),
    )
    op.add_column(
        "workshop_schedules",
        sa.Column("can_late_come_min", sa.Integer(), nullable=False),
    )
    op.drop_column("workshop_schedules", "can_earlier_come")
    op.drop_column("workshop_schedules", "can_late_come")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshop_schedules",
        sa.Column("can_late_come", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "workshop_schedules",
        sa.Column(
            "can_earlier_come", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("workshop_schedules", "can_late_come_min")
    op.drop_column("workshop_schedules", "can_earlier_come_min")
    # ### end Alembic commands ###
