"""Edited quan_t and quan

Revision ID: d0321d354675
Revises: a74903a69b40
Create Date: 2025-01-09 12:05:29.746620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0321d354675'
down_revision: Union[str, None] = 'a74903a69b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quan', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quan_t', sa.Float(), sa.Computed('(quan / 1000.0)::DOUBLE PRECISION', persisted=True), nullable=False))
    op.add_column('orders', sa.Column('quan_released', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quan_released_t', sa.Float(), sa.Computed('(quan_released / 1000.0)::DOUBLE PRECISION', persisted=True), nullable=False))
    op.add_column('orders', sa.Column('quan_booked', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quan_booked_t', sa.Float(), sa.Computed('(quan_booked / 1000.0)::DOUBLE PRECISION', persisted=True), nullable=False))
    op.add_column('orders', sa.Column('quan_left', sa.Integer(), sa.Computed('quan - quan_booked - quan_released', persisted=True), nullable=False))
    op.add_column('orders', sa.Column('quan_left_t', sa.Float(), sa.Computed('(quan - quan_booked - quan_released) / 1000.0', persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quan_left_t')
    op.drop_column('orders', 'quan_left')
    op.drop_column('orders', 'quan_booked_t')
    op.drop_column('orders', 'quan_booked')
    op.drop_column('orders', 'quan_released_t')
    op.drop_column('orders', 'quan_released')
    op.drop_column('orders', 'quan_t')
    op.drop_column('orders', 'quan')
    # ### end Alembic commands ###
