"""Add Workshop Id to Material

Revision ID: d21ca7453cd2
Revises: 04885350c86a
Create Date: 2024-12-28 16:57:59.607139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21ca7453cd2'
down_revision: Union[str, None] = '04885350c86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('workshop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'materials', 'workshops', ['workshop_id'], ['id'], onupdate='cascade', ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'workshop_id')
    # ### end Alembic commands ###
