"""Add Workshop Payment Return Id to Order

Revision ID: dff5a33f1f81
Revises: 7a4f26cd1735
Create Date: 2024-12-28 17:30:18.906738

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dff5a33f1f81"
down_revision: Union[str, None] = "7a4f26cd1735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("payment_return_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "orders",
        "payment_returns",
        ["payment_return_id"],
        ["id"],
        onupdate="cascade",
        ondelete="set null",
    )
    op.drop_column("orders", "checked_payment_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "checked_payment_by",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "payment_return_id")
    # ### end Alembic commands ###
