"""Add OperationModel

Revision ID: e6fd840a58ca
Revises: cd6ed654c657
Create Date: 2024-12-28 12:31:16.342900

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6fd840a58ca"
down_revision: Union[str, None] = "cd6ed654c657"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations", "role_value", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations", "role_value", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    # ### end Alembic commands ###
