"""Added some file_id to 5 tables

Revision ID: eecc875f981b
Revises: b62c29b92bd6
Create Date: 2024-12-26 10:46:51.029685

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eecc875f981b"
down_revision: Union[str, None] = "b62c29b92bd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factories", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "factories",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    op.add_column("materials", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "materials",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    op.add_column("organizations", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "organizations",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    op.add_column("users", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "users",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    op.add_column("vehicles", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "vehicles",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    op.add_column("workshops", sa.Column("file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "workshops",
        "files",
        ["file_id"],
        ["id"],
        onupdate="set null",
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workshops", type_="foreignkey")
    op.drop_column("workshops", "file_id")
    op.drop_constraint(None, "vehicles", type_="foreignkey")
    op.drop_column("vehicles", "file_id")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "file_id")
    op.drop_constraint(None, "organizations", type_="foreignkey")
    op.drop_column("organizations", "file_id")
    op.drop_constraint(None, "materials", type_="foreignkey")
    op.drop_column("materials", "file_id")
    op.drop_constraint(None, "factories", type_="foreignkey")
    op.drop_column("factories", "file_id")
    # ### end Alembic commands ###
