class AppTableNames:
    # TableNames
    RoleTableName = "roles"
    UserTypeTableName = "user_types"
    OrganizationTypeTableName = "organization_types"
    FileTableName = "files"
    FactoryTableName = "factories"
    WorkshopTableName = "workshops"
    MaterialTableName = "materials"
    UserTableName = "users"
    VehicleCategoryTableName = "vehicle_categories"
    VehicleColorTableName = "vehicle_colors"
    VehicleTableName = "vehicles"
    OrganizationTableName = "organizations"
    OrderStatusTableName = "order_status"
    OrderTableName = "orders"
    SAPRequestTableName = "sap_requests"
    KaspiPaymentsTableName = "kaspi_payments"


class AppModelNames:
    # Model Names
    RoleModelName = "RoleModel"
    UserTypeModelName = "UserTypeModel"
    FileModelName = "FileModel"
    OrganizationTypeModelName = "OrganizationTypeModel"
    FactoryModelName = "FactoryModel"
    WorkshopModelName = "WorkshopModel"
    MaterialModelName = "MaterialModel"
    UserModelName = "UserModel"
    VehicleCategoryModelName = "VehicleCategoryModel"
    VehicleColorModelName = "VehicleColorModel"
    VehicleModelName = "VehicleModel"
    OrganizationModelName = "OrganizationModel"
    OrderStatusModelName = "OrderStatusModel"
    OrderModelName = "OrderModel"
    SAPRequestModelName = "SapRequestModel"
    KaspiPaymentsModelName = "KaspiPaymentModel"
