class FieldConstants:
    # Columns
    STANDARD_LENGTH = 256
    PRICE_PRECISION = 10
    PRICE_SCALE = 2
    IIN_LENGTH = 12
    BIN_LENGTH = 12
    UNIQUE_PAYMENT_LENGTH = 100
    SHORT_LENGTH = 50
    SAP_ORDER_LENGTH_STRING = 20
    KASPI_TXN_LENGTH_STRING = 30
    WERKS_LENGTH = 4
    MATNR_LENGTH = 18
