from app.adapters.api.factory.factory_api import FactoryApi
from app.shared.app_route_constant import AppRouteConstant
from app.shared.path_constants import AppPathConstants


def assign_roles_to_route(app, path, roles) -> None:
    for route in app.routes:
        if route.path == path:
            if hasattr(route, "roles"):
                route.roles.extend(roles)
            else:
                route.roles = roles


def assign_roles(app) -> None:
    # Factory
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FactoryPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FactoryPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FactoryPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FactoryPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FactoryPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # File
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FilePathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FilePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FilePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.FilePathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # Material
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.MaterialPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.MaterialPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.MaterialPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.MaterialPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.MaterialPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Operations
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OperationPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OperationPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OperationPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OperationPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OperationPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Order Status
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrderStatusPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrderStatusPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrderStatusPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrderStatusPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrderStatusPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Organization
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationPathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationPathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationPathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    #Organizatiom Employee
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationEmployeePathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationEmployeePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationEmployeePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationEmployeePathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationEmployeePathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # Organization Type
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationTypePathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationTypePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationTypePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationTypePathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.OrganizationTypePathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Role
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.RolePathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.RolePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.RolePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.RolePathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.RolePathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # User
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserPathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserPathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserPathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # User Type
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserTypePathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserTypePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserTypePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserTypePathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.UserTypePathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Vehicle Category
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleCategoryPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleCategoryPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleCategoryPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleCategoryPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleCategoryPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Vehicle Color
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleColorPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleColorPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleColorPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleColorPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehicleColorPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    # Vehicle
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehiclePathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehiclePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehiclePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehiclePathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VehiclePathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # Verified User
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedUserPathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedUserPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedUserPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedUserPathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedUserPathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # Verified Vehicle
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedVehiclePathName}{AppPathConstants.IndexPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedVehiclePathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedVehiclePathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedVehiclePathName}{AppPathConstants.GetByIdPathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.VerifiedVehiclePathName}{AppPathConstants.GetByValuePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    # Workshop
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.WorkshopPathName}{AppPathConstants.IndexPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.WorkshopPathName}{AppPathConstants.CreatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.WorkshopPathName}{AppPathConstants.UpdatePathName}",
        roles=[AppRouteConstant.AdministratorTagName],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.WorkshopPathName}{AppPathConstants.GetByIdPathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )
    assign_roles_to_route(
        app=app,
        path=f"/{AppPathConstants.WorkshopPathName}{AppPathConstants.GetByValuePathName}",
        roles=[
            AppRouteConstant.AdministratorTagName,
            AppRouteConstant.ClientTagName,
            AppRouteConstant.EmployeesTagName,
        ],
    )



